server:
  port: 18080
spring:
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.mmm
  datasource:
    username: root
    #password: nagiosxi
    password: NoP@ssw0rd
    #password: root@123
    url: jdbc:mysql://39.98.137.86:3306/bydtcmonitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/bydtcmonitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/helpProject?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #url: jdbc:mysql://192.168.1.104:3306/bydtcmonitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: dataSource1
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
    #监控统计拦截的filters
    filters: stat
    #配置初始化大小/最小/最大
    initial-size: 2
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    #time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    #min-evictable-idle-time-millis: 30000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  jmx:
    enabled: false

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.szdeepwise.bydtcmonitor.entity

#showSql
logging:
  level:
    com:
      szdeepwise:
        bydtcmonitor:
          mapper: info
